"""TIMSS-compliant standard error and 95% CI for a weighted subgroup mean.

Implements the IEA TIMSS 2023 analytical method for a weighted mean of five
mathematics plausible values (PVs):

1. Full-sample weighted mean is computed separately for each of the 5 PVs
   using TOTWGT, then averaged for the point estimate.
2. Sampling variance is estimated with jackknife repeated replication (JRR)
   over JKZONE/JKREP: for each zone, one replicate doubles the weight of the
   JKREP==0 half and zeros the JKREP==1 half (and vice versa for the other
   replicate), leaving every other zone's weight untouched. The official
   TIMSS 2023 Technical Report (Chapter 13, Eq. 13.1) sums the squared
   deviation of each of the two replicate estimates from the full-sample
   estimate, per zone, and multiplies the total by 1/2 -- not 1/H or 1/(2H).
   This is done independently for each PV, then averaged across the 5 PVs.
3. Imputation variance (uncertainty from using 5 PVs instead of the latent
   ability) is the between-PV variance of the 5 full-sample estimates,
   scaled by Rubin's correction (1 + 1/5), per Technical Report Eq. 13.2.
4. Total variance = sampling variance + imputation variance; SE is its
   square root; the 95% CI uses a normal approximation (z = 1.96).

Verification status (2026-09-24): the weighted-mean and SE logic were
checked against Exhibit 1.2.1 of the TIMSS 2023 International Results in
Mathematics and Science for all five systems used by the Explorer. Calculated
national means and SEs match the published values after rounding: Australia
508.7 (3.48) vs. 509 (3.5); England 524.8 (4.54) vs. 525 (4.5); Singapore
605.3 (6.05) vs. 605 (6.1); United Arab Emirates 488.5 (1.73) vs. 489
(1.7); and United States 488.0 (4.19) vs. 488 (4.2).

This external validation establishes the implementation for national
descriptive means. The Explorer's subgroup estimates are generated by the
same documented method, but are not individually published benchmarks and
must remain descriptive; they do not support causal, invariance, or
assessment-bias claims.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

Z_95 = 1.959963984540054  # Normal-approximation two-sided 95% critical value


def timss_group_estimate(
    frame: pd.DataFrame,
    pv_columns: list[str],
    weight_column: str = "TOTWGT",
    zone_column: str = "JKZONE",
    replicate_column: str = "JKREP",
) -> dict | None:
    """Weighted mean, SE, and 95% CI for one already-filtered subgroup.

    `frame` must contain one row per student with `weight_column`,
    `zone_column`, `replicate_column`, and each column in `pv_columns`
    (TIMSS ships five plausible-value columns per subject).
    Returns None if there are no complete, positive-weight rows.
    """
    required = [weight_column, zone_column, replicate_column, *pv_columns]
    data = frame.dropna(subset=required)
    data = data.loc[data[weight_column] > 0]
    if data.empty:
        return None
    if not data[replicate_column].isin([0, 1]).all():
        raise ValueError(
            f"Expected TIMSS {replicate_column} codes 0/1, found "
            f"{sorted(data[replicate_column].unique())}."
        )

    weight = data[weight_column].to_numpy(dtype=float)
    zone = data[zone_column].to_numpy()
    side = data[replicate_column].to_numpy(dtype=int)
    values = data[pv_columns].to_numpy(dtype=float)
    pv_count = values.shape[1]

    total_weight = weight.sum()
    if total_weight <= 0:
        return None
    full_sample_estimate = (weight @ values) / total_weight

    # Precompute per-(zone, side) weight and weight*value sums once, so each
    # zone's two jackknife replicates are O(1) lookups rather than rebuilding
    # and re-summing a full weight array per replicate.
    weighted_values = values * weight[:, None]
    frame_sums = pd.DataFrame(
        {"weight": weight, **{f"pv{i}": weighted_values[:, i] for i in range(pv_count)}}
    )
    frame_sums["zone"] = zone
    frame_sums["side"] = side
    zone_side_sums = frame_sums.groupby(["zone", "side"]).sum()

    total_weighted_values = weighted_values.sum(axis=0)
    jrr_sum_of_squares = np.zeros(pv_count)

    for zone_id in np.unique(zone):
        zone_rows = zone_side_sums.loc[zone_id] if zone_id in zone_side_sums.index.get_level_values(0) else None
        side0 = zone_side_sums.loc[(zone_id, 0)] if (zone_id, 0) in zone_side_sums.index else None
        side1 = zone_side_sums.loc[(zone_id, 1)] if (zone_id, 1) in zone_side_sums.index else None

        weight0 = side0["weight"] if side0 is not None else 0.0
        weight1 = side1["weight"] if side1 is not None else 0.0
        pv_cols = [f"pv{i}" for i in range(pv_count)]
        values0 = side0[pv_cols].to_numpy(dtype=float) if side0 is not None else np.zeros(pv_count)
        values1 = side1[pv_cols].to_numpy(dtype=float) if side1 is not None else np.zeros(pv_count)

        outside_weight = total_weight - weight0 - weight1
        outside_values = total_weighted_values - values0 - values1

        for keep_weight, keep_values in ((weight0, values0), (weight1, values1)):
            replicate_denominator = outside_weight + 2.0 * keep_weight
            if replicate_denominator <= 0:
                continue
            replicate_numerator = outside_values + 2.0 * keep_values
            replicate_estimate = replicate_numerator / replicate_denominator
            jrr_sum_of_squares += (replicate_estimate - full_sample_estimate) ** 2

    sampling_variance_per_pv = 0.5 * jrr_sum_of_squares  # TIMSS Technical Report Eq. 13.1
    sampling_variance = float(sampling_variance_per_pv.mean())

    point_estimate = float(full_sample_estimate.mean())
    if pv_count > 1:
        between_pv_variance = float(np.var(full_sample_estimate, ddof=1))
    else:
        between_pv_variance = 0.0
    imputation_variance = (1.0 + 1.0 / pv_count) * between_pv_variance  # Eq. 13.2 (Rubin's rules)

    total_variance = sampling_variance + imputation_variance
    if total_variance < 0:
        return None
    standard_error = float(np.sqrt(total_variance))

    return {
        "weighted_mean": round(point_estimate, 1),
        "se": round(standard_error, 2),
        "ci_low": round(point_estimate - Z_95 * standard_error, 1),
        "ci_high": round(point_estimate + Z_95 * standard_error, 1),
        "unweighted_n": int(len(data)),
        "zone_count": int(np.unique(zone).size),
    }
